---
title: "EDAV-Project2"
author: "Team"
date: "February 18, 2016"
output: html_document
---
#Introduction 
For this report we will be diving into the global issue of Flood Events. The intial goal of the paper will be to investigate the datasets to better understand 
```{r, warnings = FALSE, message=FALSE, echo = FALSE}
library(dplyr)
library(ggplot2)
library(maps)
library(grid)
library(gridExtra)
setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Homework2/EDAV_Project2_Code")
```


```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
df = readRDS("GlobalFloodsRecord_modified.rds")

require(ggplot2)
world_map <- map_data("world")


df1 = df[,c("Centroid X","Centroid Y")]
colnames(df1)[which(names(df1) == "Centroid X")] <- "CentroidX"
colnames(df1)[which(names(df1) == "Centroid Y")] <- "CentroidY"

df1$CentroidX=as.numeric(levels(df1$CentroidX))[df1$CentroidX]
df1$CentroidY=as.numeric(levels(df1$CentroidY))[df1$CentroidY]
df1 = df1[complete.cases(df1$CentroidX),]

col.nacheck3 = data.frame(colSums(is.na(df1)))

p <- ggplot() + coord_fixed() + xlab("") + ylab("")
base_world_messy <- p + geom_polygon(data=world_map, aes(x=long, y=lat, group=group), 
                                     colour="light green", fill="light green")

base_world_messy
cleanup <- 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        axis.line = element_line(colour = "white"), legend.position="none",
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())

base_world <- base_world_messy + cleanup

base_world + ggtitle("World Map")
map_data = base_world +geom_point(data=df1, aes(x=CentroidX, y=CentroidY), colour="Red",fill="Pink",pch=21, size=2, alpha=I(0.5)) + ggtitle("World Map of Global Flood Events from 1985 to 2003")

map_data

```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Homework2/EDAV_Project2_Code")

df = readRDS("GlobalFloodsRecord.rds")
df$Displaced = as.numeric(df$Displaced)
df$Dead = as.numeric(df$Dead)
df$Country = as.factor(df$Country)
df$Centroid.X = as.numeric(as.character(df$Centroid.X))
df$Centroid.Y = as.numeric(as.character(df$Centroid.Y))
df$Magnitude..M... = as.numeric(as.character(df$Magnitude..M...))
df$Affected.sq.km = as.numeric(as.character(df$Affected.sq.km))
df$Duration.in.Days = as.numeric(as.character(df$Duration.in.Days))

ele = readRDS("elevation.RDS")
df = cbind(df,ele)


#setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Homework2/EDAV_Project2_Code/Project2")


startend = read.csv("Start_End.csv", header = TRUE)
df$Began = as.Date(startend$Start, "%d-%b-%y") 
df$Ended = as.Date(startend$End, "%d-%b-%y") 

month_clean <- data.frame(do.call('rbind', strsplit(as.character(df$Began),"-")))
colnames(month_clean) = c("Year", "Month", "Day")

df$Year = as.factor(month_clean$Year)
df$Month = as.factor(month_clean$Month)
df$Day = as.factor(month_clean$Day)


```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
displaced_count = df[,c("Country", "Displaced")]%>%
  group_by(Country) %>%
  summarize(Displaced = sum(Displaced))

displaced_order = order(displaced_count$Displaced,decreasing  = TRUE)
top10_dis = displaced_count[displaced_order[1:10],]


death_toll = df[,c("Country", "Dead")]%>%
  group_by(Country) %>%
  summarize(Dead = sum(Dead))

death_order = order(death_toll$Dead,decreasing  = TRUE)
top10_death = death_toll[death_order[1:10],]


flood_count = df[,c("Country", "Register..")]%>%
  group_by(Country) %>%
  summarize(count = n())

flood_count_order = order(flood_count$count,decreasing  = TRUE)
top10_flood = flood_count[flood_count_order[1:10],]

```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}


# colors <- brewer.pal(10, "Spectral")
# 
# #Find colors associtated with labels and apply the color palet
# for(i in 1:10){
#   top10_flood$color[i] = colors[i]
#   top10_death$color[i] = colors[i]
# }


a = ggplot(top10_dis, aes(x = factor(Country), y = Displaced)) +
  geom_bar(stat = "identity")+
  coord_flip()+
  ylab("Number of Displaced")+
  xlab("Country")+ theme(legend.position="none")

b = ggplot(top10_death, aes(x = factor(Country), y = Dead)) +
  geom_bar(stat = "identity")+
  coord_flip()+
  ggtitle("Top 10 Countries: Death Toll")+
  ylab("Number of Deaths")+
  xlab("Country")+ theme(legend.position="none")
c  = ggplot(top10_flood, aes(x = factor(Country), y = count)) +
  geom_bar(stat = "identity")+
  coord_flip()+
  ggtitle("Top 10 Countries: Flood Events")+
  ylab("Numer of Flood Events")+
  xlab("Country")+ theme(legend.position="none")

```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
#dev.off()
#dev.new()
  MainTitle = "Plots of Variables vs Elevation"
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(4, 1, heights = unit(c(0.25, 1,1,1), "null"))))
  grid.text(MainTitle, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
  print(a, vp = viewport(layout.pos.row = 2, layout.pos.col = 1),newpage=FALSE)
  print(b, vp = viewport(layout.pos.row = 3, layout.pos.col = 1),newpage=FALSE)
  print(c, vp = viewport(layout.pos.row = 4, layout.pos.col = 1),newpage=FALSE)


```


```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center}
#The following is to use the google API to determine elevations
#library(rgbif)
#bobkey = "AIzaSyD-8g3l-VX8TyUUI2wHUyLGBrWYQaBj-vs"
#ele = data.frame(t(rbind(df$Centroid.X, df$Centroid.Y)))
#colnames(ele) = c("decimalLongitude","decimalLatitude")
#test = elevation(ele, ele$decimalLatitude, ele$decimalLongitude, key = bobkey)
#newdf = cbind(df,test)

```

We then began to look for correlations between elevation and different aspects of teh flooding events.
```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
  
  #Split between northen and southern
southern = df$latitude < 0
df$hem[southern] = "Southern"
df$hem[!southern] = "Northern"

filtered = filter(df, elevation>0)


a = ggplot(filtered, aes(elevation)) +
    geom_density(aes(group=hem, colour=hem, fill=hem),alpha=0.3)

f = ggplot(filtered, aes(x=elevation, y=Duration.in.Days)) +
    geom_point(alpha = .25) +    # Use hollow circles
   geom_smooth()+
  ylab("Duration.in.Days")+
  xlab("Elevation")



```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}

#Over entire time
a = ggplot(df, aes(x = (Began))) +
    geom_density(aes( colour="#F8766D", fill="#F8766D"),alpha=0.3) +
  #ggtitle("Top 10 Cou+ntries: Death Toll")+
    labs(y = "Density") + theme(legend.position="none")+
      theme(axis.title.x = element_blank()) +ggtitle("Total Time Period")

#Over entire time by hemisphere



b = ggplot(df, aes(x = (Began))) +
    geom_density(aes(group=hem, colour=hem, fill=hem),alpha=0.3) +
  #ggtitle("Density Plot: Month - Red = Northern, Blue = Southern")+ 
    theme(axis.title.x = element_blank()) + theme(legend.position="none")+
  ylab("Density")

#Over entire time by month

df$Month = as.numeric(month_clean$Month)

c = ggplot(df, aes(x = (Month))) +
    geom_density(aes( colour="#F8766D", fill="#F8766D"),alpha=0.3) +
  #ggtitle("Top 10 Cou+ntries: Death Toll")+
  theme(legend.position="none")+ 
    theme(axis.title.y = element_blank())+      
  theme(axis.title.x = element_blank()) + ggtitle("Grouped by Month")



#Over entire time by month by hemisphere

d = ggplot(df, aes(x = (Month))) +
    geom_density(aes(colour=hem, fill=hem),alpha=0.3) +
  theme(axis.title.y = element_blank(),axis.title.x = element_blank())+
  theme(legend.title=element_blank())

e = ggplot(df, aes(x = (Began))) +
    geom_density(aes(group=Severity.., colour=Severity.., fill=Severity..),alpha=0.3) +
  #ggtitle("Top 10 Cou+ntries: Death Toll")+ 
  theme(legend.position="none")+
  labs(y = "Density")+
  xlab("Total Time Period")

f = ggplot(df, aes(x = (Month))) +
    geom_density(aes(group=Severity.., colour=Severity.., fill=Severity..),alpha=0.3) +
    #ggtitle("Top 10 Cou+ntries: Death Toll") + 
    theme(axis.title.y = element_blank())+
  xlab("Grouped by Month")
```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center'}
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(6, 2, heights = unit(c(0.2,1,0.2,1,0.2,1), "null"))))
  
  #grid.text(MainTitle, vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
  
  MainTitle = "Density Plots of Flood Events"
  grid.text(MainTitle, vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
  print(a, vp = viewport(layout.pos.row = 2, layout.pos.col = 1),newpage=FALSE)
  print(c, vp = viewport(layout.pos.row = 2, layout.pos.col = 2),newpage=FALSE)
  MainTitle = "Differences between hemispheres"
  grid.text(MainTitle, vp = viewport(layout.pos.row = 3, layout.pos.col = 1:2))
  print(b, vp = viewport(layout.pos.row = 4, layout.pos.col = 1),newpage=FALSE)
  print(d, vp = viewport(layout.pos.row = 4, layout.pos.col = 2),newpage=FALSE)
  MainTitle = "Severity"
  grid.text(MainTitle, vp = viewport(layout.pos.row = 5, layout.pos.col = 1:2))
  print(e, vp = viewport(layout.pos.row = 6, layout.pos.col = 1),newpage=FALSE)
  print(f, vp = viewport(layout.pos.row = 6, layout.pos.col = 2),newpage=FALSE)

```



```{r}
a = ggplot(filtered, aes(x=elevation, y=Displaced)) +
    geom_point(alpha = .25) +    # Use hollow circles
    geom_smooth(method=lm)+
  ylab("Displaced")+
  xlab("Elevation")            # Add a loess smoothed fit curve with confidence region
b = ggplot(filtered, aes(x=elevation, y=Dead)) +
    geom_point(alpha = .25) +    # Use hollow circles
   geom_smooth(method=lm)+
  ylab("Dead")+
  xlab("Elevation")
c = ggplot(filtered, aes(x=elevation, y=Affected.sq.km)) +
    geom_point(alpha = .25) +    # Use hollow circles
   geom_smooth(method=lm)+
  ylab("Affected Square km")+
  xlab("Elevation")
d = ggplot(filtered, aes(x=elevation, y=Magnitude..M...)) +
    geom_point(alpha = .25) +    # Use hollow circles
   geom_smooth()+
  ylab("Magnitude")+
  xlab("Elevation")

```

```{r}
dev.off()
  MainTitle = "Plots of Variables vs Elevation"
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(3, 2, heights = unit(c(0.25, 1,1), "null"))))
  grid.text(MainTitle, vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
  print(a, vp = viewport(layout.pos.row = 2, layout.pos.col = 1),newpage=FALSE)
  print(b, vp = viewport(layout.pos.row = 2, layout.pos.col = 2),newpage=FALSE)
  print(c, vp = viewport(layout.pos.row = 3, layout.pos.col = 1),newpage=FALSE)
  print(d, vp = viewport(layout.pos.row = 3, layout.pos.col = 2),newpage=FALSE)
```


```{r}

filt = newdf$elevation > 4000
high = newdf[filt,]

```

```{r}
#one bin for every year
b = ggplot(df, aes(Began)) +
  geom_histogram(binwidth = 31)+
  geom_density(alpha=.2, fill="#FF6666")

```


```{r}
library(wordcloud)
library(dplyr)
library(stringr)
library(tm)
words = df$Notes.and.Comments..may.include.quoted.headlines.from.copyrighted.news.stories..for.internal.research.purposes.only.
words = as.character(words)

splitting = strsplit(words,"\\s+")



splitting2 = unlist(splitting)
splitting_regex = str_replace_all(splitting2, "[^[:alnum:]]", "")
splitting_regex = str_replace_all(splitting_regex, "[0-9 ]+", "")


stopWords <- stopwords("en")

stopwordindex = splitting_regex %in% stopWords
splitting_filter = splitting_regex[!stopwordindex]
count = 1
length_v = vector(length = length(splitting_filter))


count = 1
for(i in (splitting_filter)){
  if(nchar(i)>3){
    length_v[count] = TRUE
  }else{
    length_v[count] = FALSE
  }
  count = count + 1
}



splitting3 = data.frame(splitting_filter[length_v])
splitting3$count = 1

colnames(splitting3) = c("Word","Count")

grop_by.descriptor <- group_by(splitting3,Word)
word_count <- summarise(grop_by.descriptor,count = n())

word_count_filt = filter(word_count, count >100)

set.seed(1)
require(RColorBrewer)

#words  = as.character(word_count$Descriptor)
wordcloud(freq = word_count_filt$count,word =  word_count_filt$Word,rot.per = 0.15,min.freq =20,colors=brewer.pal(8, "Dark2"))
```

```{r}
library(chron)
library(RColorBrewer)
library(lattice)

library(ncdf4)
library(RNetCDF)
setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Homework2/")

ncin <- open.nc("NOAA_Daily_phi_500mb.nc")

print.nc(ncin)
dat<-read.nc(ncin)
z = dat$phi[ , , 2]
ylat<-dat$Y
time = dat$T
xlon<-dat$X
xlon = xlon -180

#Close file


```



```{r}
library(fields)


library(maptools)

data(wrld_simpl)

#Define min/max values to plot and colors for plotting
zmin=0.

zmax=20.

clevs<-c(0,2,4,6,8,10,12,14,16,18,20,50)

ccols<-c("#5D00FF", "#002EFF","#00B9FF","#00FFB9" ,"#00FF2E","#5DFF00","#E8FF00", "#FF8B00","red", "#FF008B","#E800FF")

palette(ccols)

#Plot image  (see result in Figure 3)

dev.off()
dev.new()
z = dat$phi[ , , 1]
ylat =ylat[order(ylat)]
image.plot(xlon,ylat,z,col=palette(ccols))
plot(wrld_simpl,add=TRUE)

start_date <- as.Date("1-Apr-2002", "%d-%b-%Y")

nextdate = start_date
for(i in c(1:1000)){
  test = filter(df, nextdate > Began & nextdate < Ended & Centroid.Y>=35)
  print(dim(test))
  print(nextdate)
  if(length(dim(test)[1]) > 0){
    a = test
    date_a = nextdate
    break
  }else{
  }
  nextdate = nextdate + 1
}

library(stats)
 
```



```{r}
coords = xy.coords(xlon, ylat, recycle=TRUE)

ratio = length(xlon)/length(ylat)
y = spline(ylat,n = length(ylat)*8)$y
x = spline(xlon,n = length(y)*ratio)$y


```

```{r, warnings = FALSE, message=FALSE, echo = FALSE, fig.align='center',eval=FALSE}
width = 100
heigth = 5
windows.options(width=width, height=height)
mar <- par("mar"); mar[c(2, 4)] <- 0

setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/photos")
zmax = max(z)
zmin = min(z)
time = dat$T

#1948-01-01
start_date_phi <- as.Date("1948-01-01", "%Y-%m-%d")
start_date_floods <- as.Date("1985-01-01", "%Y-%m-%d")
start_date_plots  <- as.Date("2003-01-01", "%Y-%m-%d")

start_date_plots2  <- as.Date("2005-03-02", "%Y-%m-%d")

offset = as.numeric(start_date_floods - start_date_phi)
offset2 = as.numeric(start_date_plots - start_date_phi)
time2 = time[offset2:length(time)]
time3 = time2[1:2]
start_date = start_date_phi + offset2-1

#Begining date of FLOODS 1985-01-01
plotdf = filter(df,Centroid.Y>=35)
count = 1
for(i in seq(min(time3),max(time3),1) ){
  nextdate = (start_date + count)
  print(nextdate)
  name = paste("world",i,".png",sep='')
  png(name,width=600,height=350)
  z2 = dat$phi[ , , i]

      mydf = data.frame()
      for(i in c(1:length(z2[,1]))){
        ys = spline(z2[i,],n = length(y))$y
        mydf = rbind(mydf, ys)
      }
      nmydf = data.frame()
      for(i in c(1:length(mydf[1,]))){
        ys = spline(mydf[,i],n = length(x))$y
        nmydf = rbind(nmydf, ys)
      }
      z_test = t(as.matrix(nmydf))
      #z_test = (as.matrix(nmydf))

      y_ord =y[order(y)]

  zmax = max(z)
  zmin = min(z)
      image.plot(x,y_ord,z_test,col= rainbow(200)) #col=palette(ccols))
      plot(wrld_simpl,add=TRUE)
  main_title = paste("This is a plot of ", (format(nextdate, format="%B %d %Y")))
  
  test = filter(plotdf, nextdate >= Began & nextdate <= Ended)
  if(length(dim(test)[1]) > 0){
    a = test
    date_a = nextdate
    points(x = a$Centroid.X, y = a$Centroid.Y,cex = 3, pch= 19)
  }else{
  }
  mtext(main_title,side = 3)
  dev.off()
  count = count + 1
}


make.mov <- function(){
     system("convert *.png -set delay 1/2  2003-OCT.gif")
     #1/1 is 1 second per 2 frames
}

make.mov()



```

